[package]
name = "netsblox-vm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
std-embedded-time = "0.1.0"

[dependencies]
no-std-compat = { version = "0.4.1", features = ["alloc"] }
derive_builder = "0.11.2"
embedded-time = "0.12.1"
netsblox-ast = "=0.2.3"
slotmap = "1.0.6"
libm = "0.2.2"