name: Code Coverage

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --ignore-filename-regex 'main.rs|cli.rs|test/' --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: true
